### ISSUE TITLE
Feature Request: Customize Text color and Placeholder color

### ISSUE THREAD

**Issue by tylerjroach** [aws-amplify/amplify-ui-swift-authenticator#101]
Currently, TextField's in the Authenticator component do not have theme-able text colors and placeholder text colors.

**Comment by tylerjroach** [comment]
WIP here: https://github.com/aws-amplify/amplify-ui-swift-authenticator/pull/100

**Comment by ruisebas** [comment]
This has been released in **[1.2.3](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.2.3)**:
- The text colour maps to `theme.colors.foreground.secondary`
- The placeholder colour maps to `theme.colors.foreground.disabled`
