### ISSUE TITLE
User is logged out when app launched on offline

### ISSUE THREAD

**Issue by sasaar** [aws-amplify/amplify-ui-swift-authenticator#103]
**Describe the bug**

If user launches the app in offline mode and access token is expired, user is logged out (even if refresh token is still valid). It obvious that access token cannot be refreshed as phone is offline, but could there be some other way to handle. As refresh token is still valid, access token could be refreshed when phone appears again online.

This is problematic when access token validity period is short.

**Steps To Reproduce**

1. Log into the app
2. Set phone offline and close (kill) the app
3. Wait until access token validity time expires (e.g. 1h)
4. Launch app again

**Actual behaviour:**
User sees login screen. User can continue using the app after wifi/data enabled and user has logged again into the app.

**Expected behaviour:**
User lands to the app as logged in. No network request can be done as access token not valid and phone in offline. As refresh token is still valid, after user enables wifi/data (phone online again), access token is refreshed and user can continue using the app normally (no need to login).

**Comment by thisisabhash** [comment]
Hello,

Would you be able to post the verbose logs by enabling it while you're trying to reproduce the issue? 
```
Amplify.Logging.logLevel = .verbose
```

Also, could you post your `amplifyconfiguration.json` file with sensitive information removed so that we can replicate the scenario locally.

**Comment by ruisebas** [comment]
Hi @sasaar, I was able to reproduce the issue and I'm working on a fix.

**Comment by sasaar** [comment]
Thanks for your prompt answer. Do you still need logs from our side or can you proceed with your own logs/debugging?

**Comment by ruisebas** [comment]
@sasaar the fix has been released in **[1.2.3](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.2.3)**.

If after upgrading you're still facing problems, please either re-open this issue or create a new one and provide the logs.

Thanks!
