### ISSUE TITLE
Birthdate Attribute Mismatch between Cognito Settings and Authenticator UI

### ISSUE THREAD

**Issue by CdrAppDev** [aws-amplify/amplify-ui-swift-authenticator#33]
[](url)**Description:**
When using the Amplify UI Authenticator for SwiftUI, I've encountered an inconsistency between the Cognito user pool settings and the authenticator UI. Specifically, the birthdate attribute is set as required in my Cognito user pool settings. However, in the user interface of the authenticator, the birthdate field is presented as optional.

**Steps to Reproduce:**

Set the birthdate attribute as required in Cognito user pool settings.
Implement the Amplify UI Authenticator in a SwiftUI application.
Attempt to sign up without filling in the birthdate.
Actual Behavior:
The user is able to successfully create an account in the Cognito user pool without providing a birthdate.

**Expected Behavior:**
The birthdate should be required in the authenticator UI to match the Cognito user pool settings. If a user tries to sign up without providing a birthdate, they should receive an error and the account should not be created.

![Screenshot 2023-08-24 at 9 57 01 AM](https://github.com/aws-amplify/amplify-ui-swift-authenticator/assets/142937326/7ac63c4e-73bb-4cea-8064-b0075cc44760)

![Screenshot 2023-08-24 at 9 58 45 AM](https://github.com/aws-amplify/amplify-ui-swift-authenticator/assets/142937326/c920f59d-e7ca-477f-9de8-a8438530c601)

**Comment by ruisebas** [comment]
Thanks for opening this issue.
I was able to reproduce it and will work on a fix.
