### ISSUE TITLE
Issue with label text and validation for email only login

### ISSUE THREAD

**Issue by sumuhans** [aws-amplify/amplify-ui-swift-authenticator#50]
I am using the "Use existing resources without the CLI" option as detailed [here](https://docs.amplify.aws/swift/build-a-backend/auth/existing-resources/) 
I have configured cognito to use only email and password for login. However when using amplify-ui, it displays "username" instead of "email' in both the "create account" and "login" screens. No email validation is performed either.

<img width="395" alt="image" src="https://github.com/aws-amplify/amplify-ui-swift-authenticator/assets/39094976/2db81143-caa6-49c8-9d48-a2ebb0727258">

My configuration file

```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "<MyPoolID>",
            "AppClientId": "<client id>",
            "Region": "eu-west-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "passwordProtectionSettings": {
                "passwordPolicyMinLength": 8,
                "passwordPolicyCharacters": ["Requires Uppercase"]
            }
          }
        }
      }
    }
  }
}

```

**Comment by ruisebas** [comment]
Hi @sumuhans, thanks for opening this issue.

The Authenticator reads the login attribute from the `usernameAttributes` array in the `amplifyconfiguration.json` file,  defaulting to `USERNAME` if none is present.

So you just need to add it to your file:

```json
"Auth": {
  "Default": {
    "authenticationFlowType": "USER_SRP_AUTH",
    "usernameAttributes": ["EMAIL"],
    "passwordProtectionSettings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": ["REQUIRES_UPPERCASE"]
    }
  }
}
```

Somewhat related, the password policy value you should use is `REQUIRES_UPPERCASE`, so I've fixed that in the example above.

Please try it out and let us know if you're still seeing issues.
