### ISSUE TITLE
phonenumber field validation/error not shown correctly

### ISSUE THREAD

**Issue by manishsoldi** [aws-amplify/amplify-ui-swift-authenticator#55]
Which Creating an account, in phonenumber field you can paste iphone keyboard suggested phone number in (408) 555-1212 format, which now can be submitted. But when error comes back from backend you can see ios log saying it is a phone number format error but on the screen you see a generic error that something went wrong. 

Can we fix this to show the proper that phone number is in wrong format.

Thanks
Manish

**Comment by ruisebas** [comment]
Hi @manishsoldi, thanks for reporting this issue.

We'll take a look and post updates here

**Comment by ruisebas** [comment]
The fix has been released in [1.1.1](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.1.1).
Please update your dependency.

Thanks!
