### ISSUE TITLE
public class ConfirmResetPasswordState is missing public func move(to ..)

### ISSUE THREAD

**Issue by merbula** [aws-amplify/amplify-ui-swift-authenticator#64]
Hi,

public class ConfirmResetPasswordState is missing following function:

`public func move(to initialStep: AuthenticatorInitialStep) {
        authenticatorState.move(to: initialStep)
 }`

Because of that I cannot set initial step in my custom reset password confirmation view to desired step (.signIn). Similar function can be found from public class ResetPasswordState implementation.

**Comment by ruisebas** [comment]
Hi @merbula, thanks for opening this issue.
We'll take a look and post and update once we have more info.

**Comment by ruisebas** [comment]
Authenticator's version [1.1.2](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.1.2) now exposes an API to manually transition the component to another initial step through the `AuthenticatorState` environment object.

You should be able to do something like this:
```swift
struct CustomConfirmResetPasswordView: View {
    @Environment(\.authenticatorState) private var authenticatorState
    @ObservedObject var state: ConfirmResetPasswordState

    var body: some View {
        Button("Go Back") {
            authenticatorState.move(to: .resetPassword)
        }
    }
}
```
