### ISSUE TITLE
Wrong error message when device is offline

### ISSUE THREAD

**Issue by merbula** [aws-amplify/amplify-ui-swift-authenticator#79]
Hi,

The Authenticator is showing wrong error message when device is offline and user tries to Sign-in. 
"Sorry, something went wrong" error message is shown. "Please check your connectivity" would be expected error in offline case.

In can see that there is a valid text defined in localizable strings but it is not used in this case. I´m using Authenticator with custom UI.

Log from console:

Unable to Sign In
The operation couldn’t be completed. (Amplify.AuthError error 2.)
AuthError: Unexpected error occurred with message: 
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-swift/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't.
Caused by:
Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x3027bd7a0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWResolutionReportKey=Resolved 0 endpoints in 0ms using unknown from cache, _NSURLErrorNWPathKey=unsatisfied (No network route)}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask

**Comment by ruisebas** [comment]
Thanks for opening this issue. We will investigate and post updates here

**Comment by ruisebas** [comment]
This has been fixed in [1.1.4](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.1.4)
