### ISSUE TITLE
Is there way to show sign in view after resetting new password?

### ISSUE THREAD

**Issue by merbula** [aws-amplify/amplify-ui-swift-authenticator#81]
Hi,

After resetting the password user is signed in directly (in happy case). Is there way to force user to sign in after resetting the new password? I´m using Authenticator state machine with custom UI´s.

Thanks!

**Comment by lawmicha** [comment]
Hi @merbula, do you mean to automatically sign in the user with the new password that they entered in the reset password flow?

**Comment by ruisebas** [comment]
@merbula once the reset password workflow is successfully completed, the Authenticator will automatically sign in the user with the new password.

There is no way to change this.

**Comment by merbula** [comment]
Why this is different compared to Android? Is there plan to change this functionality similar to Android? Android is redirecting user to sign in view after resetting the password and user needs to sign in with the new password.

**Comment by ruisebas** [comment]
Thanks for pointing out the discrepancy between platforms. 
We will discuss among the teams and post updates here.

**Comment by ruisebas** [comment]
The Swift Authenticator matches the behaviour of the **Flutter** one, when after successfully resetting a password the user is automatically signed in.

The Android team opened a feature-request to update their behaviour to match: https://github.com/aws-amplify/amplify-ui-android/issues/160
