### ISSUE TITLE
Error description could be more precise when resetting password several times on a row

### ISSUE THREAD

**Issue by merbula** [aws-amplify/amplify-ui-swift-authenticator#83]
Hi,

When user resets the password several times on a row, following error is given:  "Sorry, something went wrong".
The error description should be more instructive for the user.

I´m calling functions resetPassword() and confirmResetPassword() from custom UI´s.

Thanks!

**Comment by merbula** [comment]
Not sure if this is your job but.. Also tested the update functionality too.

Updating the password with several times on a row does not give any error for the user. In my opinion user should be informed with appropriate error text.

Using Amplify.Auth.update(oldPassword: xxx, to: xxx) to update password.

**Comment by ruisebas** [comment]
Hi @merbula, thanks for opening this issue.

Regarding your first question, could you please enable verbose logging (by adding `Amplify.Logging.logLevel = .verbose` before `Amplify.configure()`) and either share the logs with us or check what is the underlying error? The most likely reason is that there is no default string defined for said error.

Regarding your second question, the Authenticator doesn't really support the update password flow, so I was wondering how you are testing it. 
Having said that, the error message you shared seems to be pretty informative.

**Comment by merbula** [comment]
My apologies, forgot to add log in my first question. Here is something:

Failed execution for Auth.resetPasswordAPI with error:
AuthError: Attempt limit exceeded, please try after some time.
Recovery suggestion: Make sure that the request made to the particular AWS resources are under the resource quota limits
Caused by:
limitExceeded
Unable to initialize a password reset
The operation couldn’t be completed. (Amplify.AuthError error 1.)

Like you said, there is not default error text specified so it is giving the unknown text.

**Comment by ruisebas** [comment]
The Authenticator only ships with messages for the most common errors, as you can see [here](https://github.com/aws-amplify/amplify-ui-swift-authenticator/blob/main/Sources/Authenticator/Resources/en.lproj/Localizable.strings#L165-L176).

However since this is a known Cognito error, the Authenticator allows you to define a custom error message by having a key with the format `authenticator.cognitoError.{CognitoError}` in to your app's `Localizable.strings` file.

For this particular example, it would be:

```swift
"authenticator.cognitoError.limitExceeded" = "You've reached the limit of requests. Please wait a couple of minutes and try again";
```

**Comment by merbula** [comment]
Yes, i have seen those common errors. But is there a list available for the all possible Cognito errors? This .limitExceeded came from the bushes.
