### ISSUE TITLE
AuthenticatorBaseState loses set credentials when app goes to background and then comes back to foreground

### ISSUE THREAD

**Issue by sasaar** [aws-amplify/amplify-ui-swift-authenticator#88]
Description:

App uses Authenticator with custom UI to signup, signin and reset password. The following bug appears when reseting password: AuthenticatorBaseState seems to lose already set credentials  (username) if app goes to background and then comes back to foreground (new instance created?).

Steps to reproduce:
1. App uses Authenticator with custom UI views to signin, signup and reset password:

```swift
var body: some Scene {
    WindowGroup {
        Authenticator(
                signInContent: { signInState in
                    MySignInView(state: signInState)
                },
                signUpContent: { signUpState in
                   MySignUpView(state: signUpState)
                },
                confirmSignUpContent: { confirmSignUpState in
                    MySignUpConfirmationView(state: confirmSignUpState)
                },
                resetPasswordContent: { resetPasswordState in
                    MyResetPwdView(state: resetPasswordState)
                },
                confirmResetPasswordContent: { confirmResetPwdState in
                    MyResetPwdConfirmView(state: confirmResetPwdState)
                }
            ) { _ in
                ContentView()
            }
      }
}
```

2. Select reset password. Enter Email and then put app to the background. Open app again, entered username appears still in Email text field, press continue.

3. Reset password code is sent to your email. Enter confirmation code and new password, and select continue. "Sorry, something went wrong" message appears. By debugging, it can be seen that **state (ConfirmResetPasswordState)** has lost credentials and username required for **state.confirmResetPassword()** is empty string.

![Screenshot 2024-08-13 at 8 40 43](https://github.com/user-attachments/assets/e4baeca7-002b-4612-8d86-74fcc40e097e)

![Screenshot 2024-08-13 at 8 40 25](https://github.com/user-attachments/assets/2de4ce6f-abb3-456f-a244-5aaea2dea68a)

Note. Same problem appears when confirming signup.

**Comment by ruisebas** [comment]
@sasaar I was unable to reproduce this issue when providing custom `resetPasswordContent` and `confirmResetPasswordContent` views to the Authenticator.
I tried both on the simulator and an actual device, and the component was able to proceed successfully.

`credentials.username` is set when [the `ResetPasswordState.username` property is edited](https://github.com/aws-amplify/amplify-ui-swift-authenticator/blob/main/Sources/Authenticator/States/ResetPasswordState.swift#L16), so I suspect you might have something in your app that is causing the Authenticator to be re-drawn when the app either moves to the background or foreground.

For example, something sightly similar was happening when having an `EnvironmentObject` that automatically published a property: https://github.com/aws-amplify/amplify-ui-swift-authenticator/issues/52

**Comment by sasaar** [comment]
Thanks for the advice, it indeed appeared that environment property forced view to refresh causing state (AuthenticatorBaseState) to be reinitialised.
