### ISSUE TITLE
Refresh token expired

### ISSUE THREAD

**Issue by merbula** [aws-amplify/amplify-ui-swift-authenticator#90]
Hi,

We have found following issue with refresh token expiration and session´s isSignedIn property.

Steps to reproduce issue:
1. Log in to the application
2. Put app background or close it
3. Wait until refresh token is expired
4. Open the app again, content view appears
5. When getting session info with Amplify.Auth.fetchAuthSession() -> session's isSignedIn property is still 'true'

Expected result: Session's isSignedIn should be 'false'? Login view should be visible and user should login again?

<img width="880" alt="Screenshot 2024-08-20 at 12 37 23" src="https://github.com/user-attachments/assets/e6fabe54-13c8-4ede-916b-c7aa94d84bbd">

**Comment by ruisebas** [comment]
Hi @merbula! What you are describing is the current behaviour of Amplify: When a refresh token expires, `isSignedIn` will be remain `true`.

What version of the Authenticator are you using? Last week we released [1.1.6](https://github.com/aws-amplify/amplify-ui-swift-authenticator/releases/tag/1.1.6) to properly handle this situation: when the token expires the users will be signed out and asked to sign in again.
